version: "3"
services:
  frontend:
    container_name: react_production
    build:
      context: .
      dockerfile: ./docker/production/react/Dockerfile
    # environment:
    #   - WATCHPACK_POLLING=true
    #   - viteの環境変数を設定する場合は、.env.productionファイルを作成して、VITE_で始まる変数を定義する
    tty: true
    ports:
      - "80:80"
    command: nginx -g daemon off;

  backend:
    container_name: spring_production
    build:
      context: .
      dockerfile: ./docker/production/spring/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/team_b?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Tokyo
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_SERVER_PORT=8080
      - TZ=Asia/Tokyo
    ports:
      - "8080:8080"
    depends_on:
      - database
    command: sh -c "/wait-for-it.sh database:3306 -- java -jar /app/backend/build/libs/backend-0.0.1-SNAPSHOT.jar"

  database:
    container_name: mysql_production
    build:
      context: .
      dockerfile: ./docker/production/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_volume:/var/lib/mysql # 保存領域
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team_b
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
