version: "3"
services:
  frontend:
    container_name: react
    build:
      context: .
      dockerfile: ./docker/development/react/Dockerfile
    volumes:
      - ./frontend/:/app/frontend
      # コンテナ内のnode_modulesをホストに上書きしない(無名バインドでOS間のバイナリ変換エラーを解消)
      - /app/frontend/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "5173:5173"
    command: npm run dev

  backend:
    container_name: spring
    build:
      context: .
      dockerfile: ./docker/development/spring/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    command: ./gradlew bootRun --no-daemon

  database:
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/development/mysql/Dockerfile
    ports:
    - '3306:3306'
    volumes:
      - ./mysql_volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: team_b
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
